/**
 * Pre-build script that embeds the current git commit hash into the app.
 * Run this before building: `node scripts/embed-commit.js`
 */
const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const commitHash = execSync("git rev-parse HEAD").toString().trim();
const commitShort = commitHash.slice(0, 7);
const branch = execSync("git rev-parse --abbrev-ref HEAD").toString().trim();
const commitDate = execSync("git log -1 --format=%ci").toString().trim();
const commitMessage = execSync("git log -1 --format=%s").toString().trim();

const config = {
  commitHash,
  commitShort,
  branch,
  commitDate,
  commitMessage,
  buildTime: new Date().toISOString(),
};

const outputPath = path.join(__dirname, "..", "constants", "buildInfo.ts");

const content = `// Auto-generated by scripts/embed-commit.js — do not edit manually
export const BUILD_INFO = ${JSON.stringify(config, null, 2)} as const;
`;

fs.writeFileSync(outputPath, content, "utf-8");
console.log(`✅ Build info embedded: ${commitShort} (${branch})`);
